[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prefer-offline"]

[phases.build]
cmds = ["pnpm install && pnpm run build"]

[start]
cmd = "cd ./frontend && pnpm run start:prod"
